-- ============================================================================
-- Do-Otter RAG schema + exact seed snapshot
-- Generated by: node scripts/generate-rag-supabase-sql.cjs
-- Source of truth: lib/rag/evidence.ts, lib/rag/situations.ts
-- Safe to run repeatedly: code-managed rows are synced without deleting external rows.
-- ============================================================================

begin;

-- 앱 기본 스키마가 이미 있다면 채팅 출처 메타데이터도 함께 마이그레이션한다.
-- chat_messages가 아직 없는 신규 프로젝트에서는 supabase/schema.sql 실행 시 생성된다.
do $$
begin
  if to_regclass('public.chat_messages') is not null then
    alter table public.chat_messages add column if not exists rag_meta jsonb;
  end if;
end
$$;

create table if not exists public.rag_evidence (
  id              text primary key check (id ~ '^R[1-9][0-9]*$'),
  topic           text not null,
  domain          text,
  tags            text[] not null default '{}',
  evidence_level  text,
  source_title    text not null,
  publisher       text not null,
  source_year     text not null,
  claim           text not null,
  usage           text not null,
  caution         text not null,
  url             text,
  managed_by      text not null default 'external',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists public.rag_situations (
  id               text primary key check (id ~ '^A[1-9][0-9]*$'),
  name             text not null,
  trigger_text     text not null,
  detectable       text not null,
  detect_note      text,
  answer_type      text not null,
  medical          boolean not null default false,
  purpose          text not null,
  template         text not null,
  expected_action  text not null,
  generation       text not null,
  chat_enabled     boolean not null default false,
  rag_enabled      boolean not null default false,
  managed_by       text not null default 'external',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.rag_situation_evidence (
  situation_id  text not null references public.rag_situations(id) on delete cascade,
  evidence_id   text not null references public.rag_evidence(id) on delete cascade,
  rank          integer not null check (rank > 0),
  managed_by    text not null default 'external',
  created_at    timestamptz not null default now(),
  primary key (situation_id, evidence_id),
  unique (situation_id, rank)
);

create table if not exists public.rag_corpus_meta (
  corpus_key            text primary key,
  source_version        text not null,
  retrieval_mode        text not null,
  retrieval_weights     jsonb not null,
  emergency_situation   text not null references public.rag_situations(id),
  evidence_count        integer not null,
  situation_count       integer not null,
  rag_situation_count   integer not null,
  chat_situation_count  integer not null,
  mapping_count         integer not null,
  synced_at             timestamptz not null default now()
);

alter table public.rag_evidence
  add column if not exists managed_by text not null default 'external';
alter table public.rag_situations
  add column if not exists managed_by text not null default 'external';
alter table public.rag_situation_evidence
  add column if not exists managed_by text not null default 'external';

create index if not exists rag_evidence_domain_idx
  on public.rag_evidence(domain);
create index if not exists rag_evidence_tags_idx
  on public.rag_evidence using gin(tags);
create index if not exists rag_situations_rag_idx
  on public.rag_situations(rag_enabled, chat_enabled);
create index if not exists rag_mapping_evidence_idx
  on public.rag_situation_evidence(evidence_id);

insert into public.rag_evidence (
  id, topic, domain, tags, evidence_level, source_title, publisher, source_year,
  claim, usage, caution, url, managed_by
)
values
  ('R1', '장시간 컴퓨터 작업과 미세 휴식', null, '{}'::text[], null, 'Computer Workstations: Work Process and Recognition', 'U.S. Occupational Safety and Health Administration (OSHA)', '확인 2026', '장시간의 정적 자세와 반복 작업은 목, 어깨 등 국소 피로를 높일 수 있으며, 짧고 잦은 휴식과 자세 변화가 회복에 도움이 된다. OSHA eTool은 컴퓨터 작업 매시간 5분 정도 화면에서 벗어나도록 제안한다.', '60분 연속 공부 뒤 5분간 일어나 걷거나 가볍게 움직이도록 제안한다.', '직업성 인간공학 안내이며 개인의 질환을 진단하는 자료가 아니다. 통증이 심하거나 지속되는 경우에 대한 진료 지시는 별도 안전 규칙으로 처리한다.', null, 'do-otter-code'),
  ('R2', '좌식 행동과 신체활동', null, '{}'::text[], null, 'WHO Guidelines on Physical Activity and Sedentary Behaviour', 'World Health Organization (WHO)', '2020', '성인은 좌식 행동 시간을 제한하고 가능한 범위에서 신체활동으로 대체해야 하며, 적은 양의 움직임도 전혀 하지 않는 것보다 낫다.', '오래 앉아 공부한 뒤 짧게라도 일어나 움직이도록 권한다.', 'WHO 자료는 ''매시간 5분'' 같은 정확한 휴식 간격을 정하지 않는다. 구체적인 60분/5분 조건은 R1과 앱 운영 기준으로 함께 사용해야 한다.', null, 'do-otter-code'),
  ('R3', '디지털 눈 피로와 화면 휴식', null, '{}'::text[], null, 'Healthy Vision Month Social Media Library – Digital Eye Strain and Screen Time Tips', 'National Eye Institute, U.S. National Institutes of Health (NEI/NIH)', '2026', '화면을 오래 보면 눈이 피로해질 수 있으며, 20분마다 20초 동안 약 20피트(약 6m) 떨어진 곳을 보는 20-20-20 휴식법을 안내한다.', '웹앱 내 화면 사용 20분 후 20초 동안 약 6m 밖을 보도록 제안한다.', '눈 질환의 치료법으로 표현하지 않는다. 증상이 지속되거나 시력 변화가 있으면 일반 알림이 아닌 별도의 의료 안전 안내가 필요하다.', null, 'do-otter-code'),
  ('R4', '성인 권장 수면 시간', null, '{}'::text[], null, 'About Sleep', 'U.S. Centers for Disease Control and Prevention (CDC)', '2024', 'CDC는 18~60세 성인에게 하루 7시간 이상의 수면을 권장하며, 충분한 수면과 수면의 질이 건강에 중요하다고 설명한다.', '수면이 7시간 미만이거나 심하게 졸린다고 입력한 사용자가 밤샘으로 새 범위를 늘리지 않고 수면 시간을 확보하도록 안내한다.', '개인별 필요 수면 시간은 다를 수 있다. 불면이나 과도한 졸림이 지속되는 경우는 의료진 상담이 필요할 수 있음을 별도 규칙으로 둔다.', null, 'do-otter-code'),
  ('R5', '카페인의 수면 영향', null, '{}'::text[], null, 'Caffeine', 'European Food Safety Authority (EFSA)', '2015', '일부 성인은 취침에 가까운 시간에 카페인 100mg을 섭취해도 수면 시간과 수면 양상이 영향을 받을 수 있다.', '취침에 가까운 시간에는 카페인을 추가로 마시기보다 물이나 무카페인 음료를 고르도록 안내한다.', '100mg을 모든 사람에게 동일한 기준으로 적용하지 않는다. 카페인 민감도, 임신, 복용 약물과 건강 상태에 따라 영향이 다르다.', null, 'do-otter-code'),
  ('R6', '카페인 섭취량과 개인차', null, '{}'::text[], null, 'Spilling the Beans: How Much Caffeine is Too Much?', 'U.S. Food and Drug Administration (FDA)', '확인 2026', 'FDA는 대부분의 성인에서 하루 400mg까지는 일반적으로 부정적 영향과 연관되지 않는 양으로 소개하지만, 카페인 민감도와 제거 속도에는 큰 개인차가 있다고 설명한다. 과도한 섭취는 좋지 않다.', '카페인을 공부를 위한 무조건적 해결책으로 권하지 않고, 취침이 가까우면 추가 섭취를 피하도록 한다.', '400mg을 권장량이나 모든 사람에게 안전한 상한으로 표현하지 않는다. 임신/수유, 특정 질환/약물 복용자는 의료진과 상의가 필요하다.', null, 'do-otter-code'),
  ('R7', '스트레스 상황의 짧은 자기조절', null, '{}'::text[], null, 'Doing What Matters in Times of Stress: An Illustrated Guide', 'World Health Organization (WHO)', '2020', 'WHO는 스트레스에 대처하기 위한 실용적 자기관리 기술로 현재 감각과 주변에 주의를 돌리는 그라운딩 등을 제시하며, 짧은 시간에 연습할 수 있다고 설명한다.', '스트레스가 높다고 입력한 사용자가 주변에서 보이는 것과 신체 감각을 짧게 확인한 뒤 공부 목표를 5분으로 줄이도록 안내한다.', '일반적 스트레스 관리 자료이며 불안장애 등 질환을 진단하거나 치료하는 답변으로 사용하지 않는다. 극심한 고통, 자해 위험 등의 표현은 별도 안전 대응으로 넘긴다.', null, 'do-otter-code'),
  ('R8', '컴퓨터 작업의 중립 자세', null, '{}'::text[], null, 'Computer Workstations eTool: Good Working Positions', 'U.S. Occupational Safety and Health Administration (OSHA)', '확인 2026', 'OSHA는 머리와 몸통을 정렬하고 어깨를 이완하며, 손/손목/전완을 일직선에 가깝게 두는 중립 자세가 근육/힘줄/골격의 부담을 줄이는 데 도움이 된다고 설명한다.', '목이나 어깨 또는 손목 불편감이 있을 때 작업을 잠시 멈추고 머리, 어깨, 손목의 중립 자세를 점검하도록 안내한다.', '직업성 인간공학 안내이며 통증 원인을 진단하지 않는다. 통증, 저림이 반복되거나 악화될 때는 계속 사용하도록 권하지 말고 의료진 확인을 안내한다.', null, 'do-otter-code'),
  ('R9', '컴퓨터 작업의 불편감과 짧은 휴식', null, '{}'::text[], null, 'Office Environments and Your Safety', 'National Institute for Occupational Safety and Health (NIOSH), U.S. CDC', '확인 2026', 'NIOSH는 오래 앉거나 서 있거나 어색한 자세를 피하도록 작업 환경을 조정해야 하며, 컴퓨터 작업에서 매시간 짧은 휴식이 불편감 감소에 도움이 될 수 있다고 설명한다.', '오랜 공부나 불편감 입력 시 같은 자세와 입력 작업을 끊고 일어나 움직이며, 작업 환경과 자세를 조정하도록 제안한다.', '직장 환경 연구를 학생 공부 상황에 일반화하는 자료다. 정확한 치료법이나 모든 사람에게 동일한 휴식 간격으로 표현하지 않는다.', null, 'do-otter-code'),
  ('R10', '수면 부족과 학습 집중 기능', null, '{}'::text[], null, 'Sleep Deprivation and Deficiency: How Sleep Affects Your Health', 'National Heart, Lung, and Blood Institute (NHLBI), U.S. NIH', '2022', '수면 부족은 학습, 집중, 기억, 판단과 반응에 문제를 일으킬 수 있고, 여러 날 수면이 부족하면 수행 저하와 실수가 누적될 수 있다.', '밤샘을 계획하거나 여러 날 수면 부족이 반복된 사용자에게 새 범위를 늘리기보다 복습 범위를 제한하고 수면 시간을 확보하도록 안내한다.', '개인의 상태를 진단하지 않는다. 특정 시간의 수면이 성적을 보장한다고 표현하지 말고, 지속적인 과도한 졸림이나 수면 문제는 의료진 상담이 필요할 수 있음을 별도로 안내한다.', null, 'do-otter-code'),
  ('R11', '응급상황 경고 신호', null, '{}'::text[], null, 'Recognizing Medical Emergencies', 'MedlinePlus, U.S. National Library of Medicine', '확인 2026', '호흡곤란, 지속되는 가슴 통증/불편감, 실신/의식 소실, 의식 상태 변화 등은 즉시 의료 도움을 받아야 할 수 있는 응급 경고 신호로 제시된다.', '갑작스럽고 심한 증상을 입력하면 공부를 즉시 중단하고 혼자 버티지 않도록 하며 주변 사람과 응급 도움을 연결한다.', '증상만으로 질환을 추정하지 않는다. 응급 가능성이 있는 상황에서 스트레칭/휴식/공부 재개를 먼저 권하지 않는다.', null, 'do-otter-code'),
  ('R12', '대한민국 119 구급신고', null, '{}'::text[], null, '119 구급신고 요령', '대한민국 소방청', '확인 2026', '소방청은 환자가 발생하면 119에 알리고 위치, 아픈 부위와 상황, 의식, 호흡 여부, 나이, 지병, 복용약 등을 전달하며 전화를 끊지 않고 의료지도를 받도록 안내한다.', '응급 증상 입력 시 사용자에게 주변에 알리고 119에 연락하도록 하며, 신고 시 위치와 의식, 호흡 상태를 전달하도록 안내한다.', '대한민국 사용자를 전제로 한 안내다. 해외 사용자는 현지 응급전화로 대체해야 하며, 앱이 응급의료기관을 대신할 수 없음을 명확히 한다.', null, 'do-otter-code'),
  ('R13', '효과적인 학습기법의 비교', 'learning', array['시험계획', '인출연습', '분산학습', '복습', '오답']::text[], 'review', 'Improving Students'' Learning With Effective Learning Techniques', 'Psychological Science in the Public Interest', '2013', '10가지 학습기법을 폭넓게 검토한 결과, 연습시험과 분산학습은 다양한 학습 조건에서 높은 활용도를 보였다. 반면 밑줄 긋기와 단순 재독은 전반적 활용도가 낮게 평가됐다.', '시험 계획을 단순 읽기 위주로 채우지 않고, 자료를 덮고 답해 보는 인출 연습과 날짜를 나눈 복습을 포함하도록 제안한다.', '모든 과목과 학습목표에 동일한 방법이 최선이라는 뜻은 아니다. 이해가 부족한 새 내용에는 설명과 예시 학습이 먼저 필요할 수 있다.', 'https://doi.org/10.1177/1529100612453266', 'do-otter-code'),
  ('R14', '교실 환경의 인출 연습', 'learning', array['퀴즈', '자기시험', '인출연습', '피드백', '오답']::text[], 'meta-analysis', 'Testing (quizzing) boosts classroom learning: A systematic and meta-analytic review', 'Psychological Bulletin', '2021', '222개 연구와 48,478명의 자료를 종합했을 때, 교실에서의 퀴즈와 인출 연습은 다시 읽기 등 비교 조건보다 학업 성취를 중간 정도 향상시켰다. 효과는 피드백, 반복 횟수, 시험 형식과 자료의 일치 등에 따라 달라졌다.', '핵심 내용을 보지 않고 짧게 답한 뒤 정답과 오답을 확인하는 복습 구간을 일정에 넣도록 제안한다.', '인출 시도만 반복하고 오답을 방치하지 않는다. 이해·추론처럼 단순 회상과 다른 목표에는 설명, 문제 해결과 피드백을 함께 사용한다.', 'https://pubmed.ncbi.nlm.nih.gov/33683913/', 'do-otter-code'),
  ('R15', '분산학습과 복습 간격', 'learning', array['분산학습', '간격반복', '시험계획', '장기기억']::text[], 'meta-analysis', 'Distributed practice in verbal recall tasks: A review and quantitative synthesis', 'Psychological Bulletin', '2006', '184편의 논문에 포함된 317개 실험을 분석한 결과, 학습을 한 번에 몰아서 반복하는 것보다 시간 간격을 둔 학습이 장기 기억에 유리했다. 유리한 학습 간격은 최종적으로 기억해야 하는 기간과 함께 달라졌다.', '남은 학습 범위를 하루에 몰지 않고 시험 전 여러 날에 걸쳐 다시 만나도록 일정을 나눈다.', '모든 사용자에게 적용되는 고정 간격을 제시하지 않는다. 시험까지 남은 기간, 과목, 현재 숙련도에 맞춰 간격을 조정한다.', 'https://pubmed.ncbi.nlm.nih.gov/16719566/', 'do-otter-code'),
  ('R16', '실제 수업 맥락의 분산학습', 'learning', array['분산학습', '교실', '시험대비', '복습']::text[], 'meta-analysis', 'The Distributed Practice Effect on Classroom Learning: A Meta-Analytic Review of Applied Research', 'Behavioral Sciences', '2025', '실제 교실 자료를 사용한 22개 보고서의 31개 효과크기를 종합했을 때, 하루 이상 간격을 둔 분산학습이 몰아 학습보다 기억 유지에 중간 정도 유리했다.', '시험 전 남은 날짜가 허용한다면 같은 핵심 범위를 서로 다른 날에 다시 확인하도록 계획한다.', '포함 연구 수와 과목 구성이 제한적이므로 정확한 효과크기를 개인에게 보장하지 않는다. 시험 전날처럼 시간이 거의 없으면 간격을 새로 만들 수 없다는 점도 고려한다.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12189222/', 'do-otter-code'),
  ('R17', '교차 연습의 적용 조건', 'learning', array['교차연습', '문제풀이', '수학', '범주구별', '시험대비']::text[], 'meta-analysis', 'Similarity matters: A meta-analysis of interleaved learning and its moderators', 'Psychological Bulletin', '2019', '59개 연구를 종합한 결과, 서로 다른 유형을 섞어 연습하는 교차 연습은 전체적으로 중간 정도 효과가 있었지만 자료 유형에 따라 차이가 컸다. 수학 과제에는 작은 이점이 있었으나 설명문에는 효과가 불명확했고 단어 학습에는 묶음 연습이 더 유리했다.', '유사한 문제 유형을 구별해야 하는 수학·문제풀이에서는 유형을 적절히 섞되, 암기 단어와 설명문에는 자동 적용하지 않는다.', '교차 연습을 모든 과목의 보편적 원칙으로 표현하지 않는다. 기본 풀이를 아직 모르는 단계에서는 한 유형의 예시와 연습이 먼저 필요할 수 있다.', 'https://pubmed.ncbi.nlm.nih.gov/31556629/', 'do-otter-code'),
  ('R18', '메타인지와 자기조절학습', 'learning', array['계획', '점검', '회고', '자기조절', '학습전략']::text[], 'guideline', 'Metacognition and Self-Regulated Learning', 'Education Endowment Foundation (EEF)', '2025', 'EEF는 학습자가 과제와 자신의 강·약점, 사용할 전략을 인식하고 학습을 계획·점검·평가하도록 명시적으로 지원할 것을 권고한다. 전략은 특정 과목과 실제 과제 안에 연결할 때 더 효과적일 수 있다.', '주간 기록이나 미완료 일정을 보여 준 뒤 무엇이 막혔는지 한 가지를 고르고, 다음 계획에서 바꿀 전략을 구체화하도록 돕는다.', '공부시간만으로 이해도나 학습전략의 질을 단정하지 않는다. 사용자에게 확인 질문을 하고 실제 과목과 과제에 맞춰 제안한다.', 'https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/metacognition', 'do-otter-code'),
  ('R19', '실행의도와 시작 계획', 'productivity', array['미루기', '시작', '실행계획', '언제', '어디서', 'if-then']::text[], 'review', 'Implementation Intentions', 'U.S. National Cancer Institute', '확인 2026', '실행의도는 ''상황 Y가 오면 행동 Z를 한다''처럼 기회나 장애물과 목표 행동을 연결하는 if-then 계획이다. 이런 계획은 의도를 실제 행동으로 옮기는 데 도움을 줄 수 있으며, 목표가 분명하고 활성화돼 있을 때 더 잘 작동한다.', '막연히 공부하겠다는 다짐 대신 시작 시각·장소·첫 행동을 연결한 한 문장 계획을 만들도록 제안한다.', 'if-then 계획이 동기, 시간, 필요한 자료의 부족을 자동으로 해결한다고 말하지 않는다. 실행 가능한 목표와 함께 사용한다.', 'https://dccps.nci.nih.gov/BRP/constructs/implementation_intentions/goal_intent_attain.pdf', 'do-otter-code'),
  ('R20', '목표 설정과 행동 변화', 'productivity', array['구체적목표', '목표난이도', '행동변화', '계획', '재설정']::text[], 'meta-analysis', 'Unique effects of setting goals on behavior change: Systematic review and meta-analysis', 'Journal of Consulting and Clinical Psychology', '2017', '141편의 무작위 연구에서 목표 설정은 다양한 행동 변화에 작지만 긍정적인 고유 효과를 보였다. 효과는 목표의 난이도와 공개 여부, 집단 목표 여부 등 조건에 따라 달라졌다.', '''공부하기''처럼 모호한 목표를 문제 수, 페이지, 결과물처럼 완료 여부를 확인할 수 있는 단위로 바꾼다.', '무조건 어려운 목표를 강요하지 않는다. 시간과 숙련도에 비해 비현실적인 목표는 조정하고, 사용자가 목표를 받아들일 수 있어야 한다.', 'https://pubmed.ncbi.nlm.nih.gov/29189034/', 'do-otter-code'),
  ('R21', '구체적 목표와 피드백', 'productivity', array['구체적목표', '단기목표', '피드백', '집중', '실행전략']::text[], 'review', 'Locke''s theory of goal setting', 'American Psychological Association Dictionary of Psychology', '2018', '목표설정 이론은 모호한 목표보다 구체적 목표가 활동을 더 잘 이끌며, 장기 목표를 위해 단기 목표를 사용할 수 있다고 설명한다. 목표가 작동하려면 진행 상황에 대한 적시 피드백과 행동 전략이 필요하다.', '집중이 흐려졌을 때 다음 구간에서 끝낼 한 가지 결과와 확인 시점을 정하도록 돕는다.', '구체적이라는 이유만으로 목표 달성이 보장된다고 말하지 않는다. 복잡하고 새로운 과제에는 학습목표와 전략 탐색이 먼저일 수 있다.', 'https://dictionary.apa.org/lockes-theory-of-goal-setting', 'do-otter-code'),
  ('R22', '진행 상황 기록과 목표 달성', 'productivity', array['진행점검', '기록', '회고', '목표달성', '피드백']::text[], 'meta-analysis', 'Does Monitoring Goal Progress Promote Goal Attainment?', 'Psychological Bulletin', '2016', '138개 연구와 19,951명의 자료를 종합했을 때, 진행 상황 점검을 늘리는 개입은 목표 달성을 향상시켰다. 결과를 실제로 기록하거나 보고할 때 효과가 더 큰 경향이 있었다.', '공부시간만 칭찬하지 않고 완료 범위와 계획 대비 진행을 기록한 뒤, 다음에 조정할 행동 하나를 고른다.', '점검 횟수를 과도하게 늘려 공부 자체를 방해하지 않는다. 기록은 평가나 자책이 아니라 다음 조정을 위한 정보로 사용한다.', 'https://eprints.whiterose.ac.uk/id/eprint/91437/', 'do-otter-code'),
  ('R23', '시간관리와 학업·웰빙', 'productivity', array['시간관리', '우선순위', '일정', '학업성과', '웰빙']::text[], 'meta-analysis', 'Does time management work? A meta-analysis', 'PLOS ONE', '2021', '158개 연구와 53,957명의 자료를 종합한 결과, 시간관리는 학업성취·업무수행·웰빙과 중간 정도 관련됐고 고통감과는 부적 관련을 보였다. 웰빙과의 관련성이 수행과의 관련성보다 더 크게 나타났다.', '남은 일을 전부 밀어 넣기보다 중요한 과제를 고르고, 실제 가능한 시간에 맞춰 일정을 재배치하도록 돕는다.', '대부분의 결과가 상관관계를 포함하므로 시간관리가 성적 향상을 직접 보장한다고 말하지 않는다. 개인의 여건과 과제 난이도를 함께 고려한다.', 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0245066', 'do-otter-code'),
  ('R24', '미루기 개입의 효과와 한계', 'productivity', array['미루기', '과제시작', '목표축소', '자기조절', '마감']::text[], 'meta-analysis', 'Targeting Procrastination Using Psychological Treatments', 'Frontiers in Psychology', '2018', '12개 무작위 연구를 종합했을 때 미루기를 겨냥한 심리 개입은 전체적으로 작지만 유의한 이점이 있었고 연구 간 차이가 컸다. 인지행동 접근의 하위 분석은 중간 정도 효과를 보였으나 포함 연구가 적었다.', '미루기를 성격 문제로 단정하지 않고, 과제의 첫 단계를 작게 만들거나 방해 요인과 실행 시점을 구체화하는 선택지를 제공한다.', '앱의 짧은 알림을 심리치료와 동일시하지 않는다. 지속적이고 심각한 어려움이나 정신건강 문제를 진단·치료한다고 표현하지 않는다.', 'https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2018.01588/full', 'do-otter-code'),
  ('R25', '스마트폰 알림의 주의 비용', 'focus', array['스마트폰', '알림', '방해앱', '주의', '집중']::text[], 'primary-study', 'The attentional cost of receiving a cell phone notification', 'Journal of Experimental Psychology: Human Perception and Performance', '2015', '실험에서 휴대전화 알림을 받는 것만으로도 기기를 직접 확인하지 않은 상태에서 주의가 필요한 과제 수행이 유의하게 방해됐다.', '집중 구간에는 방해 앱을 닫고 불필요한 알림을 잠시 끄거나 모아서 확인하도록 제안한다.', '단일 실험 결과를 모든 사용자와 실제 공부 성과에 그대로 일반화하지 않는다. 앱에서 정한 3분·10분 임계값의 효과를 입증하는 자료도 아니다.', 'https://pubmed.ncbi.nlm.nih.gov/26121498/', 'do-otter-code'),
  ('R26', '멀티태스킹과 과제 전환 비용', 'focus', array['멀티태스킹', '과제전환', '방해', '단일과제', '집중']::text[], 'review', 'Multitasking: Switching costs', 'American Psychological Association', '2006', '과제 전환 실험에서는 두 과제를 번갈아 수행할 때 반복 수행보다 시간이 더 걸렸고, 과제가 복잡하거나 익숙하지 않을수록 전환 비용이 커졌다. 준비 시간을 줘도 비용이 완전히 사라지지는 않았다.', '다음 공부 구간에는 한 과제만 남기고, 방해 앱에서 돌아올 때 직전에 하던 위치와 다음 한 행동을 명시한다.', '사람이 어떤 상황에서도 두 활동을 동시에 할 수 없다고 과장하지 않는다. 제품의 차단 임계값 자체를 연구 결과로 표현하지 않는다.', 'https://www.apa.org/topics/research/multitasking', 'do-otter-code'),
  ('R27', '모바일 인터넷 제한과 지속주의', 'focus', array['스마트폰차단', '모바일인터넷', '지속주의', '디지털웰빙']::text[], 'randomized-trial', 'Blocking mobile internet on smartphones improves sustained attention, mental health, and subjective well-being', 'PNAS Nexus', '2025', '사전등록 무작위 교차시험에서 2주 동안 스마트폰의 모바일 인터넷을 차단했을 때 스마트폰 사용이 줄고 객관적으로 측정한 지속주의와 주관적 웰빙이 개선됐다.', '반복 이탈이 있는 사용자가 원할 경우 다음 공부 구간에 한해 인터넷이나 특정 앱 접근을 제한하는 선택지를 제안한다.', '2주간 모바일 인터넷 전체를 제한한 연구이므로 특정 앱을 몇 분 차단하는 효과와 동일시하지 않는다. 정신건강 치료 효과로 홍보하지 않는다.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11834938/', 'do-otter-code'),
  ('R28', '짧은 휴식과 피로·수행', 'focus', array['미세휴식', '피로', '활력', '집중', '휴식']::text[], 'meta-analysis', 'Give me a break! A systematic review and meta-analysis on the efficacy of micro-breaks', 'PLOS ONE', '2022', '22개 표본을 종합한 결과 10분 이하의 짧은 휴식은 활력을 높이고 피로를 낮추는 작은 효과가 있었다. 전체 수행 향상 효과는 유의하지 않았고, 고난도 인지 과제에서는 더 긴 회복이 필요할 수 있었다.', '집중이 흐려지거나 피로하면 짧은 휴식을 선택하게 하되, 집중이 유지되는 사용자에게 일률적으로 작업을 끊도록 강제하지 않는다.', '35분, 1분, 5분 같은 앱의 시점을 보편적인 최적 집중·휴식 시간으로 표현하지 않는다. 휴식이 항상 성과를 높인다고 보장하지 않는다.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9432722/', 'do-otter-code'),
  ('R29', '푸시 알림과 과제 수행', 'focus', array['푸시알림', 'Go-NoGo', '방해', '스마트폰', '집중']::text[], 'primary-study', 'An Analysis of the Effects of Smartphone Push Notifications on Task Performance', 'Computational Intelligence and Neuroscience', '2016', 'Go/No-Go 과제 실험에서 스마트폰 푸시 알림은 과제 수행과 관련된 행동·뇌파 지표에 부정적 영향을 보였고, 과다사용 위험군에서는 후속 수행에도 영향이 관찰됐다.', '집중 세션 중 불필요한 푸시 알림을 줄이는 환경 설정을 선택지로 제공한다.', '소규모 실험의 뇌파 결과를 학업성취나 개인의 뇌 기능에 대한 진단으로 확대하지 않는다. R25의 보조 근거로 사용한다.', 'https://pubmed.ncbi.nlm.nih.gov/27366147/', 'do-otter-code'),
  ('R30', '습관과 안정된 맥락의 반복', 'habit', array['습관', '반복', '맥락', '루틴', '재시작']::text[], 'review', 'Psychology of Habit', 'Annual Review of Psychology', '2016', '습관 연구는 사람들이 목표를 추구하며 특정 맥락에서 같은 반응을 반복할 때 습관이 형성된다고 설명한다. 반복되는 맥락 단서는 행동을 더 자동적으로 이끌 수 있다.', '연속 일수 자체보다 잘 지켜진 시간·장소·앞선 행동을 찾아 다음 공부를 같은 단서에 연결한다.', '며칠 연속 수행했다는 사실만으로 습관이 완성됐다고 말하지 않는다. 반복 횟수와 자동화 속도에는 개인차가 있다.', 'https://pubmed.ncbi.nlm.nih.gov/26361052/', 'do-otter-code'),
  ('R31', '일상에서의 습관 형성 과정', 'habit', array['습관형성', '연속기록', '누락', '반복', '자동화']::text[], 'primary-study', 'How are habits formed: Modelling habit formation in the real world', 'European Journal of Social Psychology', '2010', '참가자들이 같은 맥락에서 행동을 12주 반복했을 때 자동성은 점차 증가했지만 개인차가 컸다. 한 번의 수행 기회 누락은 습관 형성 과정에 실질적인 영향을 주지 않았다.', '스트릭이 끊길 가능성을 겁주지 않고, 놓친 날이 있어도 다음 기회에 같은 단서로 재개하도록 안내한다.', '연구의 18~254일 범위를 보편적인 습관 완성 기간으로 제시하지 않는다. 연구 행동이 공부 습관과 완전히 동일하다고 가정하지 않는다.', 'https://doi.org/10.1002/ejsp.674', 'do-otter-code'),
  ('R32', '습관 형성 기간의 개인차', 'habit', array['습관기간', '개인차', '맥락안정성', '반복', '루틴']::text[], 'systematic-review', 'Time to Form a Habit: A Systematic Review and Meta-Analysis of Health Behaviour Habit Formation', 'Healthcare', '2024', '20개 건강행동 연구에서 습관 형성 기간은 사람과 행동에 따라 크게 달랐다. 반복 빈도, 안정된 맥락, 행동의 선택과 난이도 등이 습관 강도에 영향을 주는 요인으로 보고됐다.', '고정된 며칠 목표보다 사용자가 지속 가능한 최소 행동과 반복할 맥락을 고르게 한다.', '건강행동 중심 연구이며 상당수 연구의 비뚤림 위험이 높았다. 공부 습관에 정확한 형성 기간이나 효과크기를 적용하지 않는다.', 'https://pubmed.ncbi.nlm.nih.gov/39685110/', 'do-otter-code'),
  ('R33', '교육 게이미피케이션과 행동 변화', 'habit', array['게이미피케이션', '레벨', '배지', '보상', '참여']::text[], 'meta-analysis', 'Effects of Gamification on Behavioral Change in Education: A Meta-Analysis', 'International Journal of Environmental Research and Public Health', '2021', '통제집단이 있는 교육 연구를 종합했을 때 게이미피케이션은 학습 행동에 중간 정도의 긍정적 효과를 보였다. 짧은 개입의 효과가 더 컸고, 장기간 적용에서는 효과가 약하거나 부정적인 결과도 관찰됐다.', '레벨·업적·재화는 학습 행동을 보여 주는 짧은 피드백으로 사용하고, 실제 완료 범위와 다음 행동에 연결한다.', '배지나 재화가 성적 또는 장기 습관을 보장한다고 말하지 않는다. 보상을 잃는다는 압박이나 사용자 간 과도한 비교를 사용하지 않는다.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8037535/', 'do-otter-code'),
  ('R34', '칭찬의 내용과 내재적 동기', 'habit', array['칭찬', '피드백', '동기', '전략', '과정']::text[], 'review', 'The effects of praise on children''s intrinsic motivation: a review and synthesis', 'Psychological Bulletin', '2002', '칭찬은 언제나 같은 효과를 내지 않는다. 진실하게 받아들여지고, 통제 가능한 원인과 자율성·유능감을 지원하며 과도한 사회 비교를 피할 때 동기에 도움이 될 수 있다.', '''천재야'' 같은 사람 평가보다 실제로 완료한 범위, 사용한 전략, 다시 반복할 수 있는 행동을 구체적으로 짚는다.', '아동 중심 문헌을 모든 연령에 그대로 일반화하지 않는다. 빈 칭찬이나 과장된 칭찬, 성적을 보장하는 표현을 피한다.', 'https://pubmed.ncbi.nlm.nih.gov/12206194/', 'do-otter-code'),
  ('R35', '학습 피드백의 효과와 내용', 'learning', array['피드백', '진행률', '학습목표', '다음행동', '회고']::text[], 'meta-analysis', 'The Power of Feedback Revisited: A Meta-Analysis of Educational Feedback Research', 'Frontiers in Psychology', '2020', '435개 연구와 61,000명 이상의 자료를 종합했을 때 피드백은 학습에 중간 정도 효과가 있었지만 연구 간 차이가 컸다. 전달하는 정보의 내용이 효과를 크게 좌우했고, 인지·운동 결과에서 동기·행동 결과보다 영향이 컸다.', '현재 기록을 목표와 비교하고 무엇이 완료됐는지, 다음에는 무엇을 바꿀지를 구체적으로 알려 준다.', '모든 피드백이 긍정적이라고 가정하지 않는다. 단순 순위·사람 평가·막연한 칭찬보다 과제와 전략, 다음 행동에 관한 정보를 우선한다.', 'https://pubmed.ncbi.nlm.nih.gov/32038429/', 'do-otter-code'),
  ('R36', '효과적인 학습 피드백 지침', 'learning', array['피드백', '학습격차', '목표', '다음단계', '형성평가']::text[], 'guideline', 'Teacher Feedback to Improve Pupil Learning', 'Education Endowment Foundation (EEF)', '2021', 'EEF는 피드백을 학습 목표와 현재 수행 사이의 차이를 줄이기 위한 정보로 다루며, 모든 피드백이 긍정적 효과를 내는 것은 아니라고 강조한다. 학습 의도와 실제 학습 격차를 먼저 파악해야 한다.', '완료 알림에서 결과만 축하하지 않고, 목표 대비 현재 위치와 바로 이어갈 다음 한 단계를 보여 준다.', '교사가 학생에게 주는 피드백 지침을 앱 알림에 적용하는 것이므로, 앱 기록만으로 이해도와 오류 원인을 확정하지 않는다.', 'https://educationendowmentfoundation.org.uk/education-evidence/guidance-reports/feedback', 'do-otter-code'),
  ('R37', '개인화 알림과 앱 지속 사용', 'productivity', array['알림', '개인화', '지속사용', '참여', '타이밍']::text[], 'systematic-review', 'Factors Influencing Adherence to mHealth Apps', 'Journal of Medical Internet Research', '2022', '99개 연구를 검토한 결과, 사용자 필요에 맞춘 내용, 개별화된 푸시 알림, 사용하기 쉬운 안정적 설계와 보조적 지원이 앱 지속 사용에 긍정적인 요인으로 보고됐다. 다만 다수 연구는 기간이 짧은 예비 연구였다.', '알림을 반복해서 닫은 사용자의 알림 시간·빈도·내용을 이전 반응에 맞춰 줄이거나 다시 설정하도록 제안한다.', '건강 앱의 지속 사용 연구를 학습 앱에 간접 적용한다. 개인화 알림이 반드시 공부 행동이나 성적을 높인다고 말하지 않는다.', 'https://pubmed.ncbi.nlm.nih.gov/35612886/', 'do-otter-code'),
  ('R38', '리마인더와 알림 피로', 'productivity', array['알림피로', '리마인더', '참여', '빈도조절', '옵트아웃']::text[], 'systematic-review', 'Conceptualising engagement with digital behaviour change interventions', 'Translational Behavioral Medicine', '2017', '디지털 행동변화 개입 참여 문헌에서는 리마인더가 참여를 높일 수 있지만, 너무 많은 리마인더는 알림 피로 때문에 참여에 부정적 영향을 줄 수 있다고 정리한다.', '사용자가 알림을 반복해서 닫으면 더 강하게 압박하지 않고, 빈도를 낮추거나 시간 재설정·일시 중지를 선택하게 한다.', '가장 효과적인 알림 횟수를 고정 수치로 제시하지 않는다. 사용자가 원하지 않는 알림을 계속 보내도록 설계하지 않는다.', 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5526809/', 'do-otter-code')
on conflict (id) do update set
  topic = excluded.topic,
  domain = excluded.domain,
  tags = excluded.tags,
  evidence_level = excluded.evidence_level,
  source_title = excluded.source_title,
  publisher = excluded.publisher,
  source_year = excluded.source_year,
  claim = excluded.claim,
  usage = excluded.usage,
  caution = excluded.caution,
  url = excluded.url,
  managed_by = excluded.managed_by,
  updated_at = now();

insert into public.rag_situations (
  id, name, trigger_text, detectable, detect_note, answer_type, medical, purpose,
  template, expected_action, generation, chat_enabled, rag_enabled, managed_by
)
values
  ('A1', '오늘 첫 홈 화면 진입', '당일 최초 로그인 또는 4시간 이상 미접속 후 홈 화면 진입', '가능', null, '단순알람', false, '오늘 일정/D-day 인지, 첫 공부 선택', '오늘은 {예정 과목 수}개가 예정되어 있고, 가장 가까운 시험은 D-{남은 일수}야. 먼저 {첫 일정}부터 열어 보자.', '오늘 일정 확인 후 첫 과목의 공부 모드 시작', 'LLM개인화', false, false, 'do-otter-code'),
  ('A2', '공부 예정 시각 10분 전', '등록된 공부 일정 시작 10분 전', '가능', null, '단순알람', false, '시작 준비와 지연 예방', '10분 뒤 {과목} 시작이야. 책과 필요한 자료만 먼저 꺼내 두자.', '책/자료 준비 후 예정 시각에 공부 시작', 'LLM개인화', false, false, 'do-otter-code'),
  ('A3', '예정 시각이 지났지만 공부를 시작하지 않음', '등록된 일정 시작 후 5분이 지났고 공부 모드가 시작되지 않음', '가능', null, '집중유도', false, '계획 미루기 중단, 즉시 착수', '예정 시각이 5분 지났어. 지금은 {과목}을 5분만 시작해—계획 전체보다 첫 문제 하나가 우선이야.', '공부 모드 실행 후 첫 문제/첫 페이지 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A4', '공부 모드 시작', '사용자가 공부 모드 또는 타이머를 시작함', '가능', null, '집중유도', false, '첫 목표 명확화', '공부 모드 시작했어. 첫 목표는 {목표 시간}분 동안 {할 일} 하나만 끝내는 거야.', '한 가지 목표에 집중하여 첫 구간 수행', 'LLM개인화', false, false, 'do-otter-code'),
  ('A5', '35분 연속 공부', '공부 모드가 중단 없이 35분 지속됨', '가능', null, '집중유도', false, '집중 상태 점검과 흐름 유지', '35분째 이어가고 있어. 집중이 유지되면 그대로 가고, 흐려졌다면 1분만 정리한 뒤 다음 구간을 시작하자.', '집중 상태를 점검하고 계속 공부하거나 짧게 정리 후 재개', '고정문구', false, false, 'do-otter-code'),
  ('A6', '20분 연속 화면 사용', '웹앱 내 학습 화면을 20분 이상 연속 사용함', '부분가능', '웹앱 내 화면 시간만 감지', '의학적답변', true, '눈의 피로를 줄이기 위한 짧은 화면 휴식', '화면을 20분째 보고 있어. 20초 동안 약 6m 밖을 보고 눈을 쉬게 한 뒤 돌아오자.', '20초간 먼 곳을 본 후 학습 화면으로 복귀', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A7', '60분 연속 공부', '공부 모드가 중단 없이 60분 지속됨', '부분가능', '공부 시간만 감지, 자세는 미감지', '의학적답변', true, '장시간 같은 자세를 끊고 움직임 확보', '한 시간 동안 공부를 이어갔어. 5분 동안 일어나 걷거나 가볍게 몸을 움직인 뒤 다시 앉자.', '자리에서 일어나 5분간 움직인 후 공부 재개', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A8', '공부 타이머 종료', '설정한 공부 타이머가 0분이 됨', '가능', null, '단순알람', false, '학습 기록 저장과 완료 범위 확인', '타이머가 끝났어. 기록을 저장하고 끝낸 범위를 체크해 줘.', '공부 기록 저장 및 완료 범위 표시', '고정문구', false, false, 'do-otter-code'),
  ('A9', '휴식 타이머 종료', '설정한 휴식 타이머가 0분이 됨', '가능', null, '집중유도', false, '휴식 연장 방지와 공부 복귀', '쉬는 시간이 끝났어. 방금 하던 페이지로 돌아가 다음 5분만 다시 시작하자.', '기존 공부 화면으로 돌아가 타이머 재시작', '고정문구', false, false, 'do-otter-code'),
  ('A10', '공부 모드가 5분 이상 일시정지됨', '공부 모드를 일시정지한 뒤 5분 동안 재개하거나 종료하지 않음', '가능', null, '집중유도', false, '애매한 중단 상태 종료', '공부 모드가 5분째 멈춰 있어. 계속 쉴 거면 종료하고, 아니라면 지금 재개 버튼을 눌러.', '공부 모드 재개 또는 명시적으로 종료', '고정문구', false, false, 'do-otter-code'),
  ('A11', '짧은 시간에 공부가 반복 중단됨', '1시간 안에 공부 모드 일시정지/종료가 3회 이상 발생', '가능', null, '집중유도', false, '목표 축소를 통한 흐름 복구', '한 시간 안에 {중단 횟수}번 흐름이 끊겼어. 다음 구간은 {짧은 목표 시간}분으로 줄이고 한 가지 일만 끝내자.', '짧은 타이머로 한 가지 과제 재시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A12', '등록한 공부 과제 완료', '사용자가 일정 또는 할 일을 완료 처리함', '가능', null, '단순알람', false, '성과 확인과 다음 행동 연결', '{과목}의 {완료 범위}를 끝냈어. 완료 기록을 남기고 다음 일정은 하나만 확인하자.', '완료 기록 저장 후 다음 일정 1개 확인', 'LLM개인화', false, false, 'do-otter-code'),
  ('A13', '하루 공부 목표 달성', '당일 누적 공부 시간이 설정 목표 이상이 됨', '가능', null, '단순알람', false, '달성 칭찬과 의식적인 종료 선택', '오늘 목표 {목표 시간}을 채웠어. 여기서 종료할지, 남은 일정 하나를 더 할지 선택해 줘.', '공부 종료 또는 다음 일정 1개 선택', 'LLM개인화', false, false, 'do-otter-code'),
  ('A14', '하루 중간까지 공부 기록이 없음', '사용자 지정 중간 점검 시각에 예정 일정이 1개 이상이고 당일 공부 기록이 0분임', '가능', null, '집중유도', false, '첫 공부 기록 생성', '오늘 예정된 공부가 아직 시작되지 않았어. 가장 짧은 {과목}을 5분만 켜서 첫 기록부터 만들자.', '가장 짧은 과목으로 5분 공부 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A15', '하루 종료 전 미완료 일정이 남음', '사용자 지정 하루 종료 시각 1시간 전, 미완료 일정이 1개 이상 남음', '부분가능', '하루 종료 시각 설정 필요', '집중유도', false, '무리한 몰아치기 방지와 우선순위 조정', '오늘 남은 일정이 {남은 개수}개야. 전부 밀어 넣지 말고, 꼭 필요한 {우선 과제} 하나만 끝내고 나머지는 다시 배치하자.', '우선 과제 1개 수행 후 나머지 일정 재배치', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A16', '시험 D-7 도달', '등록된 시험일까지 7일 남음', '가능', null, '단순알람', false, '남은 범위 분할과 일주일 계획 착수', '시험까지 7일 남았어. 오늘은 {남은 범위}를 7일에 나눈 분량 중 첫 구간부터 시작하자.', '남은 범위를 분할하고 오늘 분량 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A17', '시험 D-1 도달', '등록된 시험일까지 1일 남음', '가능', null, '집중유도', false, '과도한 범위 확장 방지와 핵심 복습', '시험이 내일이야. 새 범위를 넓히기보다 {오답 또는 핵심 범위}를 정해진 시간만 확인하고 마무리하자.', '오답/핵심 범위 중심으로 제한된 시간 복습', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A18', '공부 공백 후 앱에 복귀', '2일 이상 공부 기록이 없다가 앱 홈 또는 공부 모드에 진입', '가능', null, '집중유도', false, '낮은 부담으로 공부 습관 재개', '공부 기록이 {공백 일수}일 비어 있었어. 복구 목표는 크게 잡지 말고 오늘 10분 기록 하나부터 다시 만들자.', '10분 타이머로 공부 재시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A19', '공부 모드 중 방해 앱 진입', '공부 모드가 켜진 상태에서 차단 목록 앱을 실행함', '불가', '모바일 앱 사용 권한 필요', '집중유도', false, '방해 앱 즉시 종료와 공부 복귀', '지금 {앱명}에 들어왔어. 필요한 용도가 아니라면 닫고, 방금 하던 {과목}으로 돌아가자.', '방해 앱 종료 후 기존 공부 화면 복귀', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A20', '방해 앱을 3분 사용', '공부 모드 중 차단 목록 앱의 연속 사용 시간이 3분에 도달', '불가', '모바일 앱 사용 권한 필요', '집중유도', false, '초기 이탈 단계에서 빠른 종료', '3분째 {앱명}을 보고 있어. 여기서 닫으면 공부 흐름을 바로 복구할 수 있어—지금 종료하자.', '방해 앱 종료 및 공부 모드 복귀', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A21', '방해 앱을 10분 사용', '공부 모드 중 차단 목록 앱의 연속 사용 시간이 10분에 도달', '불가', '모바일 앱 사용 권한 필요', '집중유도', false, '장기 이탈 중단과 작은 목표로 재시작', '10분이 지났어. 해야 할 양은 그대로이니 {앱명}을 닫고, {과목} 5분부터 다시 시작하자.', '방해 앱 종료 후 5분 공부 타이머 시작', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A22', '방해 앱 장시간/반복 사용', '공부 모드 중 방해 앱 누적 사용 60분 또는 하루 이탈 3회 이상', '불가', '모바일 앱 사용 권한 필요', '집중유도', false, '자책 없이 이탈 패턴 인지와 최소 단위 복귀', '오늘 방해 앱 이탈이 {이탈 횟수}번, 총 {사용 시간}분이야. 자책하지 말고 앱을 닫은 뒤 다음 공부 목표를 5분으로 줄여 다시 시작하자.', '방해 앱 종료 후 5분 목표로 공부 재개', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A23', '수면 시간이 부족하거나 심한 졸림을 입력', '사용자가 최근 수면 시간이 7시간 미만이라고 기록하거나 현재 심하게 졸리다고 입력', '부분가능', '사용자 입력 또는 웨어러블 연동 필요', '의학적답변', true, '무리한 밤샘 억제와 수면 시간 확보', '성인은 보통 하루 7시간 이상 수면이 권장돼. 지금 심하게 졸리면 새 범위를 늘리지 말고 오늘 잘 시간을 먼저 확보하자.', '새 학습 범위 확장을 멈추고 수면 계획 설정', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A24', '취침에 가까운 시간에 카페인을 추가하려 함', '사용자가 취침 예정 시각에 가까운 시간에 카페인 섭취를 기록하거나 추가 섭취 여부를 물음', '부분가능', '카페인/취침 시각 입력 필요', '의학적답변', true, '수면 방해 가능성 안내와 추가 섭취 회피', '취침에 가까운 카페인은 일부 성인의 수면 시간과 패턴에 영향을 줄 수 있어. 지금은 추가 섭취 대신 물이나 무카페인 음료를 선택하자.', '추가 카페인 섭취를 피하고 대체 음료 선택', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A25', '초기 설정에서 수달 성격 선택 완료', '사용자가 T수달/F수달/코치수달 중 하나를 선택하고 온보딩을 완료함', '가능', null, '단순알람', false, '선택한 코칭 방식 확인과 첫 행동 연결', '{선택 수달}로 설정했어. 앞으로 같은 기준으로 공부 흐름을 관리할게—먼저 오늘 할 일 하나를 등록하자.', '첫 공부 일정 또는 할 일 1개 등록', 'LLM개인화', false, false, 'do-otter-code'),
  ('A26', '온보딩을 마쳤지만 일정이 없음', '온보딩 완료 후 10분이 지나도 등록된 일정/할 일이 0개임', '가능', null, '집중유도', false, '빈 홈 화면에서 첫 계획 생성', '아직 등록된 공부가 없어. 오늘 꼭 해야 하는 과목 하나와 시작 시각만 먼저 넣자.', '과목/시작 시각이 포함된 첫 일정 등록', '고정문구', false, false, 'do-otter-code'),
  ('A27', '첫 공부 일정 등록 완료', '사용자가 계정 생성 후 처음으로 공부 일정을 저장함', '가능', null, '단순알람', false, '계획 생성 성과 확인과 실행 준비', '첫 일정이 등록됐어. {시작 시각}에 {과목}을 바로 시작할 수 있게 필요한 자료만 준비해 두자.', '예정 시각 전 학습 자료 준비', 'LLM개인화', false, false, 'do-otter-code'),
  ('A28', '시험 D-day 등록 완료', '사용자가 시험명과 시험일을 처음 저장함', '가능', null, '단순알람', false, '시험 일정 인지와 범위 분할 유도', '{시험명}까지 D-{남은 일수}야. 남은 범위를 확인하고 오늘 할 첫 구간 하나를 일정에 넣자.', '남은 범위를 나누고 오늘 분량 등록', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A29', '마감이 내일인데 과제를 시작하지 않음', '마감까지 24시간 이내이고 해당 과제의 공부 기록/완료 기록이 없음', '가능', null, '집중유도', false, '마감 직전 미루기 중단과 최소 착수', '{과제명} 마감이 내일이야. 전체를 끝내려 하지 말고 지금 10분 동안 첫 단계부터 시작하자.', '10분 타이머로 과제 첫 단계 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A30', '마감이 지난 미완료 과제가 있음', '등록된 마감 시각이 지났고 과제가 완료 처리되지 않음', '가능', null, '집중유도', false, '미완료 사실 확인과 일정 재배치', '{과제명} 마감이 지났지만 아직 미완료야. 지금 처리할지, 현실적인 새 마감 시각을 정할지 하나를 선택해.', '즉시 수행 또는 새 마감 시각 설정', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A31', '공부 모드를 시작했지만 목표가 비어 있음', '공부 모드 시작 후 목표 과목/범위/시간 중 핵심 정보가 입력되지 않음', '가능', null, '집중유도', false, '모호한 공부를 구체적인 한 단위로 변환', '무엇을 끝낼지 정해지지 않았어. {과목}에서 문제 수나 페이지 범위 하나만 입력하고 시작하자.', '구체적인 범위 또는 문제 수 입력', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A32', '설정한 공부 시간의 절반 도달', '현재 공부 세션이 목표 시간의 50%에 도달함', '가능', null, '단순알람', false, '진행률 확인과 남은 구간 유지', '목표 시간의 절반을 채웠어. 지금 흐름을 유지하면 남은 {남은 시간}분 뒤에 끝낼 수 있어.', '현재 과제 유지하며 남은 시간 공부', 'LLM개인화', false, false, 'do-otter-code'),
  ('A33', '예정 범위를 타이머보다 일찍 완료', '사용자가 목표 범위를 완료 처리했지만 타이머가 남아 있음', '가능', null, '단순알람', false, '성과 기록 후 의식적인 다음 선택', '예정한 {완료 범위}를 끝냈어. 남은 시간은 종료할지, 복습 한 구간을 추가할지 선택해 줘.', '세션 종료 또는 짧은 복습 선택', 'LLM개인화', false, false, 'do-otter-code'),
  ('A34', '목표 시간의 절반 전에 세션 종료', '사용자가 목표 시간의 50% 미만에서 공부 모드를 종료함', '가능', null, '집중유도', false, '중단 원인 확인과 목표 재설정', '목표 {목표 시간}분 중 {실제 시간}분에서 끝났어. 다음 세션은 가능한 시간으로 줄여 다시 잡자.', '짧아진 목표 시간으로 다음 세션 예약', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A35', '하루 공부 목표의 50% 달성', '당일 누적 공부 시간이 하루 목표의 절반에 도달함', '가능', null, '단순알람', false, '중간 성과 확인과 남은 분량 인지', '오늘 목표의 절반을 채웠어. 남은 {남은 목표 시간}분은 {다음 과목}부터 이어가자.', '다음 과목 공부 시작 또는 일정 확인', 'LLM개인화', false, false, 'do-otter-code'),
  ('A36', '하루 공부 목표를 초과 달성', '당일 누적 공부 시간이 목표보다 30분 이상 많아짐', '가능', null, '단순알람', false, '과잉 공부 자동 연장 방지와 종료 판단', '오늘 목표를 {초과 시간}분 넘겼어. 남은 일정이 필수가 아니라면 기록을 저장하고 여기서 마쳐도 돼.', '공부 기록 저장 후 종료 여부 결정', 'LLM개인화', false, false, 'do-otter-code'),
  ('A37', '3일 연속 공부 기록 달성', '3일 연속으로 최소 공부 기준을 충족함', '가능', null, '단순알람', false, '초기 습관 형성 칭찬과 다음 날 연결', '3일 연속으로 공부 기록을 만들었어. 내일도 같은 시각에 {최소 목표 시간}분만 이어가자.', '다음 날 최소 공부 일정 예약', 'LLM개인화', false, false, 'do-otter-code'),
  ('A38', '7일 연속 공부 기록 달성', '7일 연속으로 최소 공부 기준을 충족함', '가능', null, '단순알람', false, '일주일 지속 성과 확인과 유지 전략 선택', '7일 연속 기록을 채웠어. 가장 잘 지켜진 시간대를 다음 주 기본 공부 시간으로 고정하자.', '다음 주 반복 일정 설정', 'LLM개인화', false, false, 'do-otter-code'),
  ('A39', '연속 기록이 끊길 가능성이 높음', '사용자 지정 하루 종료 2시간 전이며 당일 최소 공부 기록이 없음', '부분가능', '하루 종료 시각/연속 기록 기준 설정 필요', '집중유도', false, '연속 기록 유지를 위한 최소 행동 촉진', '오늘 기록이 아직 없어. 연속 기록을 유지하려면 지금 {최소 목표 시간}분만 시작하면 돼.', '최소 목표 시간의 공부 세션 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A40', '주간 공부 리포트 생성', '한 주가 종료되고 7일간 공부 기록이 집계됨', '가능', null, '단순알람', false, '주간 패턴 확인과 개선점 1개 선택', '이번 주 총 {주간 공부 시간}, 계획 달성률은 {달성률}%야. 다음 주에는 가장 자주 미룬 {취약 시간대 또는 과목} 하나만 조정하자.', '리포트 확인 후 다음 주 개선 항목 1개 설정', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A41', '지난주보다 공부 시간이 크게 감소', '이번 주 누적 공부 시간이 지난주 같은 시점보다 30% 이상 적음', '가능', null, '집중유도', false, '감소 추세 인지와 현실적 목표 재설정', '지난주 같은 시점보다 공부 시간이 {감소율}% 줄었어. 남은 기간 목표를 다시 계산하고 오늘 가능한 한 구간부터 채우자.', '주간 목표 조정 후 오늘 세션 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A42', '지난주보다 방해 앱 사용이 감소', '이번 주 방해 앱 사용 시간이 지난주 같은 기간보다 20% 이상 감소함', '불가', '모바일 앱 사용 권한 필요', '단순알람', false, '디지털 이탈 감소 성과 강화', '이번 주 방해 앱 사용이 지난주보다 {감소율}% 줄었어. 줄어든 시간 중 일부를 {우선 과목}에 그대로 연결하자.', '절약한 시간으로 우선 과목 일정 생성', 'LLM개인화', false, false, 'do-otter-code'),
  ('A43', '하루 방해 앱 사용 목표 달성', '당일 방해 앱 누적 시간이 사용자가 정한 한도 이하로 종료됨', '불가', '모바일 앱 사용 권한 필요', '단순알람', false, '사용시간 관리 성공 확인', '오늘 방해 앱 사용을 {설정 한도} 안으로 지켰어. 잘된 시간대와 차단 설정을 내일도 그대로 유지하자.', '효과적이었던 차단 설정 유지', 'LLM개인화', false, false, 'do-otter-code'),
  ('A44', '같은 방해 앱에 짧게 반복 진입', '30분 안에 같은 차단 목록 앱을 3회 이상 실행함', '불가', '모바일 앱 사용 권한 필요', '집중유도', false, '습관적 재진입 차단과 환경 변경', '30분 안에 {앱명}을 {진입 횟수}번 열었어. 앱을 닫고 다음 공부 구간 동안만 차단 강도를 올리자.', '방해 앱 종료 후 일시적 강한 차단 적용', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A45', '수달 레벨 상승', '공부/일정 달성으로 경험치가 기준에 도달해 레벨이 오름', '부분가능', '레벨 시스템 구현 필요', '단순알람', false, '보상 피드백과 다음 목표 연결', '수달이 레벨 {현재 레벨}이 됐어. 다음 레벨까지 필요한 행동은 {다음 조건}이야.', '레벨 보상 확인 후 다음 조건 확인', 'LLM개인화', false, false, 'do-otter-code'),
  ('A46', '업적 달성', '연속 공부/누적 시간/방해 앱 감소 등 업적 조건을 충족함', '부분가능', '업적 시스템 구현 필요', '단순알람', false, '구체적 성과 시각화와 반복 강화', '{업적명} 업적을 달성했어. 이번에 성공한 행동은 {달성 조건}이니 다음에도 같은 방식으로 반복하자.', '업적 확인 후 성공 행동 반복 계획', 'LLM개인화', false, false, 'do-otter-code'),
  ('A47', '보상 재화 획득', '공부 세션 또는 일일 목표 완료로 재화가 지급됨', '부분가능', '보상 시스템 구현 필요', '단순알람', false, '즉각적 보상 제공과 기록 강화', '{보상 수량}{재화명}을 받았어. 오늘 기록은 저장됐고, 보상은 상점에서 확인할 수 있어.', '보상 내역 또는 상점 확인', 'LLM개인화', false, false, 'do-otter-code'),
  ('A48', '상점 아이템 해금 또는 구매', '레벨 조건 충족 또는 재화 사용으로 아이템을 획득함', '부분가능', '상점 시스템 구현 필요', '단순알람', false, '보상 사용 경험 제공', '{아이템명}을 획득했어. 바로 적용할지 보관할지 선택해 줘.', '아이템 적용 또는 보관 선택', 'LLM개인화', false, false, 'do-otter-code'),
  ('A49', '수달 외형 아이템 적용', '사용자가 보유 아이템을 수달 캐릭터에 장착함', '부분가능', '캐릭터 꾸미기 구현 필요', '단순알람', false, '개인화 결과 확인과 캐릭터 애착 강화', '{아이템명}을 적용했어. 이 모습으로 다음 공부 세션을 시작해 보자.', '꾸민 캐릭터와 공부 모드 시작', 'LLM개인화', false, false, 'do-otter-code'),
  ('A50', '알림을 반복해서 닫고 행동하지 않음', '공부 시작/복귀 알림을 3회 연속 닫았고 연결된 행동이 발생하지 않음', '부분가능', '알림 클릭/후속 행동 추적 필요', '집중유도', false, '과도한 압박을 줄이고 개입 방식 조정', '알림을 세 번 닫았어. 지금은 긴 계획 대신 시작 시각을 다시 정하거나 5분 목표로 낮추자.', '알림 시간 재설정 또는 5분 세션 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A51', '사용자가 집중이 안 된다고 입력', '챗봇에 집중이 안 됨/시작하기 싫음 등 공부 어려움을 직접 입력함', '가능', null, '집중유도', false, '감정 분석보다 즉시 가능한 최소 행동 제안', '지금 집중이 안 되는 상태는 확인했어. 책상 위에서 필요 없는 것 하나를 치우고 {과목} 첫 문제만 5분 동안 보자.', '환경 정리 1개 후 5분 공부 시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A52', '사용자가 스트레스나 불안이 높다고 입력', '챗봇에 스트레스/불안 때문에 공부가 어렵다고 직접 입력함', '가능', null, '의학적답변', true, '짧은 안정화 행동 후 공부 범위 축소', '스트레스가 높을 때는 잠깐 현재 감각에 주의를 돌리는 연습이 도움이 될 수 있어. 발바닥이 바닥에 닿는 감각과 주변에서 보이는 것 세 가지를 확인한 뒤, 공부 목표를 5분으로 줄여서 다시 시작하자.', '짧은 그라운딩 후 5분 목표로 재시작', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A53', '공부 중 목/어깨 불편감을 입력', '장시간 앉은 뒤 목 또는 어깨가 뻐근하거나 불편하다고 입력함', '가능', null, '의학적답변', true, '같은 자세 중단과 중립 자세 점검', '공부를 잠시 멈추고 일어나 움직인 뒤, 머리는 몸통과 일직선으로 두고 어깨 힘을 빼자. 통증이 심하거나 계속되면 참고 계속하지 말고 의료진에게 확인받자.', '짧게 움직이고 작업 자세 조정', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A54', '타이핑 중 손목/손 불편감을 입력', '키보드/마우스 사용 중 손목이나 손에 통증/저림/불편감이 있다고 입력함', '가능', null, '의학적답변', true, '반복 사용 중단과 손목 중립 자세 점검', '타이핑을 잠시 멈추고 손목과 전완을 일직선에 가깝게 두자. 통증이나 저림이 반복되거나 악화되면 사용을 계속하지 말고 의료진에게 확인받자.', '입력 작업 중단 후 손목 자세 조정', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A55', '시험 전 밤샘 공부를 계획한다고 입력', '사용자가 오늘 잠을 자지 않고 공부하겠다고 말하거나 수면 시간을 0~3시간으로 계획함', '가능', null, '의학적답변', true, '밤샘 억제와 수면을 포함한 복습 계획 전환', '수면 부족은 집중/학습/기억과 판단에 불리할 수 있어. 새 범위를 밤새 늘리기보다 핵심 복습 시간을 정하고 최소한의 수면 시간을 확보하자.', '핵심 복습 종료 시각과 수면 시작 시각 설정', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A56', '화면 사용 후 눈 불편감이나 두통을 입력', '화면 학습 중 눈의 피로/건조감/두통을 직접 입력하거나 화면 사용이 길게 지속됨', '부분가능', '증상은 사용자 입력 필요', '의학적답변', true, '화면 휴식과 증상 지속 시 안전 안내', '화면에서 눈을 떼고 20초 동안 약 6m 밖을 본 뒤 눈을 쉬게 하자. 불편감이 심하거나 시야 변화가 있거나 계속되면 화면 사용을 중단하고 의료진에게 확인받자.', '화면 휴식 후 증상에 따라 학습 중단 여부 결정', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A57', '카페인 섭취량이 많다고 입력', '당일 카페인 섭취량이 400mg을 넘었다고 기록하거나 에너지음료/커피를 반복 섭취', '부분가능', '섭취량 사용자 입력 필요', '의학적답변', true, '추가 섭취 중단과 이상 증상 확인', '카페인 반응은 사람마다 다르고, 400mg은 모두에게 안전한 목표량이 아니야. 오늘은 추가 섭취를 멈추고 물을 마시며, 두근거림이나 불면 같은 증상이 있으면 의료진에게 확인받자.', '추가 카페인 중단 및 증상 점검', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A58', '갑작스럽고 심한 증상을 입력', '가슴 통증/호흡곤란/의식 저하/실신 등 응급 가능성이 있는 증상을 직접 입력함', '가능', null, '의학적답변', true, '공부 즉시 중단과 응급 도움 연결', '공부를 바로 멈춰. 갑작스러운 가슴 통증, 호흡곤란, 실신이나 의식 저하는 응급상황일 수 있으니 혼자 버티지 말고 주변 사람에게 알리고 119에 연락해. 신고할 때 위치와 의식, 호흡 상태를 전달해 줘.', '공부 중단 후 주변 도움 요청 및 119 연락', 'RAG+LLM', true, true, 'do-otter-code'),
  ('A59', '120분 이상 연속 공부', '공부 모드가 휴식 없이 120분 이상 지속됨', '가능', null, '의학적답변', true, '장시간 정적 자세 중단과 충분한 휴식', '두 시간 동안 계속 공부했어. 지금은 타이머를 멈추고 자리에서 일어나 움직이며 화면과 입력 작업에서 벗어난 뒤 다시 시작하자.', '공부 모드 일시정지 후 움직임과 화면 휴식', 'RAG+LLM', false, true, 'do-otter-code'),
  ('A60', '수면 부족이 여러 날 반복됨', '최근 3일 연속 수면 시간이 7시간 미만으로 기록됨', '부분가능', '사용자 입력 또는 웨어러블 연동 필요', '의학적답변', true, '누적 수면 부족 인지와 일정 축소', '최근 3일 동안 수면이 계속 부족했어. 오늘 공부량을 무리하게 늘리지 말고 종료 시각을 앞당겨 수면 시간을 확보하자.', '오늘 일정 축소 후 수면 시작 시각 설정', 'RAG+LLM', false, true, 'do-otter-code')
on conflict (id) do update set
  name = excluded.name,
  trigger_text = excluded.trigger_text,
  detectable = excluded.detectable,
  detect_note = excluded.detect_note,
  answer_type = excluded.answer_type,
  medical = excluded.medical,
  purpose = excluded.purpose,
  template = excluded.template,
  expected_action = excluded.expected_action,
  generation = excluded.generation,
  chat_enabled = excluded.chat_enabled,
  rag_enabled = excluded.rag_enabled,
  managed_by = excluded.managed_by,
  updated_at = now();

delete from public.rag_situation_evidence where managed_by = 'do-otter-code';
insert into public.rag_situation_evidence (situation_id, evidence_id, rank, managed_by)
values
  ('A3', 'R19', 1, 'do-otter-code'),
  ('A3', 'R24', 2, 'do-otter-code'),
  ('A6', 'R3', 1, 'do-otter-code'),
  ('A7', 'R1', 1, 'do-otter-code'),
  ('A7', 'R2', 2, 'do-otter-code'),
  ('A11', 'R21', 1, 'do-otter-code'),
  ('A11', 'R26', 2, 'do-otter-code'),
  ('A14', 'R19', 1, 'do-otter-code'),
  ('A14', 'R24', 2, 'do-otter-code'),
  ('A15', 'R18', 1, 'do-otter-code'),
  ('A15', 'R20', 2, 'do-otter-code'),
  ('A15', 'R23', 3, 'do-otter-code'),
  ('A16', 'R13', 1, 'do-otter-code'),
  ('A16', 'R14', 2, 'do-otter-code'),
  ('A16', 'R15', 3, 'do-otter-code'),
  ('A16', 'R16', 4, 'do-otter-code'),
  ('A16', 'R17', 5, 'do-otter-code'),
  ('A16', 'R23', 6, 'do-otter-code'),
  ('A17', 'R13', 1, 'do-otter-code'),
  ('A17', 'R14', 2, 'do-otter-code'),
  ('A17', 'R17', 3, 'do-otter-code'),
  ('A18', 'R19', 1, 'do-otter-code'),
  ('A18', 'R24', 2, 'do-otter-code'),
  ('A18', 'R30', 3, 'do-otter-code'),
  ('A18', 'R31', 4, 'do-otter-code'),
  ('A19', 'R25', 1, 'do-otter-code'),
  ('A19', 'R26', 2, 'do-otter-code'),
  ('A19', 'R27', 3, 'do-otter-code'),
  ('A19', 'R29', 4, 'do-otter-code'),
  ('A20', 'R25', 1, 'do-otter-code'),
  ('A20', 'R26', 2, 'do-otter-code'),
  ('A20', 'R27', 3, 'do-otter-code'),
  ('A20', 'R29', 4, 'do-otter-code'),
  ('A21', 'R25', 1, 'do-otter-code'),
  ('A21', 'R26', 2, 'do-otter-code'),
  ('A21', 'R27', 3, 'do-otter-code'),
  ('A21', 'R29', 4, 'do-otter-code'),
  ('A22', 'R25', 1, 'do-otter-code'),
  ('A22', 'R26', 2, 'do-otter-code'),
  ('A22', 'R27', 3, 'do-otter-code'),
  ('A22', 'R29', 4, 'do-otter-code'),
  ('A23', 'R4', 1, 'do-otter-code'),
  ('A24', 'R5', 1, 'do-otter-code'),
  ('A24', 'R6', 2, 'do-otter-code'),
  ('A28', 'R13', 1, 'do-otter-code'),
  ('A28', 'R14', 2, 'do-otter-code'),
  ('A28', 'R15', 3, 'do-otter-code'),
  ('A28', 'R18', 4, 'do-otter-code'),
  ('A28', 'R23', 5, 'do-otter-code'),
  ('A29', 'R19', 1, 'do-otter-code'),
  ('A29', 'R24', 2, 'do-otter-code'),
  ('A30', 'R23', 1, 'do-otter-code'),
  ('A30', 'R24', 2, 'do-otter-code'),
  ('A31', 'R18', 1, 'do-otter-code'),
  ('A31', 'R20', 2, 'do-otter-code'),
  ('A31', 'R21', 3, 'do-otter-code'),
  ('A34', 'R20', 1, 'do-otter-code'),
  ('A34', 'R24', 2, 'do-otter-code'),
  ('A39', 'R30', 1, 'do-otter-code'),
  ('A39', 'R31', 2, 'do-otter-code'),
  ('A39', 'R32', 3, 'do-otter-code'),
  ('A40', 'R18', 1, 'do-otter-code'),
  ('A40', 'R22', 2, 'do-otter-code'),
  ('A40', 'R23', 3, 'do-otter-code'),
  ('A40', 'R35', 4, 'do-otter-code'),
  ('A40', 'R36', 5, 'do-otter-code'),
  ('A41', 'R18', 1, 'do-otter-code'),
  ('A41', 'R22', 2, 'do-otter-code'),
  ('A41', 'R23', 3, 'do-otter-code'),
  ('A41', 'R35', 4, 'do-otter-code'),
  ('A44', 'R25', 1, 'do-otter-code'),
  ('A44', 'R26', 2, 'do-otter-code'),
  ('A44', 'R27', 3, 'do-otter-code'),
  ('A44', 'R29', 4, 'do-otter-code'),
  ('A50', 'R19', 1, 'do-otter-code'),
  ('A50', 'R37', 2, 'do-otter-code'),
  ('A50', 'R38', 3, 'do-otter-code'),
  ('A51', 'R19', 1, 'do-otter-code'),
  ('A51', 'R21', 2, 'do-otter-code'),
  ('A51', 'R24', 3, 'do-otter-code'),
  ('A51', 'R26', 4, 'do-otter-code'),
  ('A52', 'R7', 1, 'do-otter-code'),
  ('A53', 'R8', 1, 'do-otter-code'),
  ('A53', 'R9', 2, 'do-otter-code'),
  ('A54', 'R8', 1, 'do-otter-code'),
  ('A54', 'R9', 2, 'do-otter-code'),
  ('A55', 'R4', 1, 'do-otter-code'),
  ('A55', 'R10', 2, 'do-otter-code'),
  ('A56', 'R3', 1, 'do-otter-code'),
  ('A57', 'R6', 1, 'do-otter-code'),
  ('A58', 'R11', 1, 'do-otter-code'),
  ('A58', 'R12', 2, 'do-otter-code'),
  ('A59', 'R1', 1, 'do-otter-code'),
  ('A59', 'R2', 2, 'do-otter-code'),
  ('A59', 'R9', 3, 'do-otter-code'),
  ('A60', 'R4', 1, 'do-otter-code'),
  ('A60', 'R10', 2, 'do-otter-code');

delete from public.rag_situations
where managed_by = 'do-otter-code' and id not in ('A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11', 'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39', 'A40', 'A41', 'A42', 'A43', 'A44', 'A45', 'A46', 'A47', 'A48', 'A49', 'A50', 'A51', 'A52', 'A53', 'A54', 'A55', 'A56', 'A57', 'A58', 'A59', 'A60');
delete from public.rag_evidence
where managed_by = 'do-otter-code' and id not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21', 'R22', 'R23', 'R24', 'R25', 'R26', 'R27', 'R28', 'R29', 'R30', 'R31', 'R32', 'R33', 'R34', 'R35', 'R36', 'R37', 'R38');

insert into public.rag_corpus_meta (
  corpus_key, source_version, retrieval_mode, retrieval_weights,
  emergency_situation, evidence_count, situation_count, rag_situation_count,
  chat_situation_count, mapping_count, synced_at
)
values (
  'default',
  'R1-R38/A1-A60',
  'curated+keyword',
  '{"tags":5,"topic":3,"usage":2,"claim":1,"sourceTitle":1,"maxChatEvidence":4}'::jsonb,
  'A58',
  38,
  60,
  35,
  25,
  97,
  now()
)
on conflict (corpus_key) do update set
  source_version = excluded.source_version,
  retrieval_mode = excluded.retrieval_mode,
  retrieval_weights = excluded.retrieval_weights,
  emergency_situation = excluded.emergency_situation,
  evidence_count = excluded.evidence_count,
  situation_count = excluded.situation_count,
  rag_situation_count = excluded.rag_situation_count,
  chat_situation_count = excluded.chat_situation_count,
  mapping_count = excluded.mapping_count,
  synced_at = excluded.synced_at;

alter table public.rag_evidence enable row level security;
alter table public.rag_situations enable row level security;
alter table public.rag_situation_evidence enable row level security;
alter table public.rag_corpus_meta enable row level security;

drop policy if exists "rag evidence read" on public.rag_evidence;
create policy "rag evidence read" on public.rag_evidence
  for select to anon, authenticated using (true);
drop policy if exists "rag situations read" on public.rag_situations;
create policy "rag situations read" on public.rag_situations
  for select to anon, authenticated using (true);
drop policy if exists "rag mapping read" on public.rag_situation_evidence;
create policy "rag mapping read" on public.rag_situation_evidence
  for select to anon, authenticated using (true);
drop policy if exists "rag corpus meta read" on public.rag_corpus_meta;
create policy "rag corpus meta read" on public.rag_corpus_meta
  for select to anon, authenticated using (true);

revoke insert, update, delete, truncate on public.rag_evidence from anon, authenticated;
revoke insert, update, delete, truncate on public.rag_situations from anon, authenticated;
revoke insert, update, delete, truncate on public.rag_situation_evidence from anon, authenticated;
revoke insert, update, delete, truncate on public.rag_corpus_meta from anon, authenticated;
grant select on public.rag_evidence to anon, authenticated;
grant select on public.rag_situations to anon, authenticated;
grant select on public.rag_situation_evidence to anon, authenticated;
grant select on public.rag_corpus_meta to anon, authenticated;

commit;

-- Verification query (expected: 38 / 60 / 35 / 25 / 97)
select
  (select count(*) from public.rag_evidence) as evidence_count,
  (select count(*) from public.rag_situations) as situation_count,
  (select count(*) from public.rag_situations where rag_enabled) as rag_situation_count,
  (select count(*) from public.rag_situations where chat_enabled) as chat_situation_count,
  (select count(*) from public.rag_situation_evidence) as mapping_count;
